/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafos;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Estudiante
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    class Nodo {

        int num;
        Nodo linkNodo;
        Subnodo linkSubnodo;
    }

    class Subnodo {

        int num;
        int peso;
        Subnodo link;
    }

    Nodo ptr;
    int[][] Adjacencia;
    File archivoM;
    File archivoL;

    public Vista() {
        initComponents();
        List.setModel(new DefaultListModel());
        ptr = null;
        archivoM = new File("archivos/matriz.txt");
        archivoL = new File("archivos/lista.txt");
    }
    Archivo file = new Archivo(archivoM, archivoL);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FileChooser = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        Matrix_Adj = new javax.swing.JTable();
        Btn_Done = new javax.swing.JButton();
        Vertices = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        List = new javax.swing.JList<>();
        Btn_Save = new javax.swing.JButton();
        Btn_Load = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Matrix_Adj.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Matrix_Adj);

        Btn_Done.setText("Crear");
        Btn_Done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DoneActionPerformed(evt);
            }
        });

        Vertices.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        Vertices.setInheritsPopupMenu(true);

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel1.setText("Numero de Vertices: ");

        List.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(List);

        Btn_Save.setText("Guardar");

        Btn_Load.setText("Cargar");
        Btn_Load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LoadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Btn_Done, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(Btn_Save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Btn_Load, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Vertices, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(21, 21, 21)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Btn_Done, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Vertices))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Btn_Load, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_Save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_DoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DoneActionPerformed
        int V = Integer.parseInt(Vertices.getModel().getValue().toString());
        Adjacencia = new int[V][V];
        Cero(V);
        for (int i = 0; i < V; i++) {
            int A = Integer.parseInt(JOptionPane.showInputDialog("Ingrese un" + " numero de aristas para el vertice " + Integer.toString(i + 1)));
            ptr = agregarLista(ptr, i + 1);
            for (int j = 0; j < A; j++) {
                int P = Integer.parseInt(JOptionPane.showInputDialog("Ingrese un" + " peso para la arista " + Integer.toString(j + 1)));
                int D = Integer.parseInt(JOptionPane.showInputDialog("Ingrese un" + " vertice a la que se va dirigir la arista " + Integer.toString(j + 1)));
                Adjacencia[i][D - 1] = P;
                ptr = agregarSublista(ptr, i + 1, D, P);
            }
        }
        DefaultTableModel model = (DefaultTableModel) Matrix_Adj.getModel();
        for (int i = 0; i < V; i++) {
            model.addColumn(i + 1);
        }
        for (int i = 0; i < V; i++) {
            Object[] Vec = new Object[V];
            for (int j = 0; j < V; j++) {
                Vec[j] = Adjacencia[i][j];
            }
            model.addRow(Vec);
        }
        mostrarMultilista(List, ptr);
        file.guardarMatriz(Matrix_Adj, archivoM);
        file.guardarLista(List, archivoL);
    }//GEN-LAST:event_Btn_DoneActionPerformed

    private void Btn_LoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LoadActionPerformed
        FileNameExtensionFilter filter
                = new FileNameExtensionFilter("Archivos .txt", "txt", "texto");
        FileChooser.setFileFilter(filter);

        // Mostrar el FileChooser
        int opcion = FileChooser.showOpenDialog(this);
        // Si el usuario escogió abrir
        if (opcion == JFileChooser.APPROVE_OPTION) {
            // Asignar archivo y nombre.
            int seleccion = JOptionPane.showOptionDialog(null, "Seleccione una opcion",
                    "Cargar archivo ", JOptionPane.YES_NO_CANCEL_OPTION,
                    JOptionPane.QUESTION_MESSAGE, null,// null para icono por defecto.
                    new Object[]{"Matriz ", "Lista "}, "Matriz");
            if (seleccion != -1) {
                switch(seleccion+1){
                    case 1:
                        archivoM = FileChooser.getSelectedFile();
                        file.cargarMatriz(Matrix_Adj, archivoM);
                        break;
                    case 2:
                        
                        break;
                }
            }

            
        }

    }//GEN-LAST:event_Btn_LoadActionPerformed

    /**
     * @param Ver
     * @param args the command line arguments
     */
    public void Cero(int Ver) {
        for (int i = 0; i < Ver; i++) {
            for (int j = 0; j < Ver; j++) {
                Adjacencia[i][j] = 0;
            }
        }
    }

    Nodo agregarLista(Nodo ptr, int elem) {
        Nodo p = new Nodo();
        p.num = elem;

        // Lista vacía -> Nueva lista
        if (ptr == null) {
            return p;
        }

        // Lista no vacía
        Nodo q = ptr;
        // Buscar último
        while (q.linkNodo != null) {
            q = q.linkNodo;
        }
        q.linkNodo = p; // Agregamos link
        return ptr;
    }

    Nodo agregarSublista(Nodo ptr, int lista, int elem, int peso) {
        Nodo p = ptr;

        while (p != null && p.num != lista) {
            p = p.linkNodo;
        }

        if (p == null) {
            return ptr;
        }

        Subnodo q = p.linkSubnodo;
        Subnodo r = new Subnodo();
        r.num = elem;
        r.peso = peso;

        // Lista vacía
        if (q == null) {
            p.linkSubnodo = r;
        } else {
            while (q.link != null) {
                q = q.link;
            }
            q.link = r;
        }
        return ptr;
    }

    void mostrarMultilista(JList lista, Nodo ptr) {
        DefaultListModel model
                = (DefaultListModel) lista.getModel();
        model.clear();

        Nodo p = ptr;
        while (p != null) {
            String Sub = "";
            Subnodo q = p.linkSubnodo;
            while (q != null) {
                Sub = Sub + "->" + q.num + "(" + q.peso + ")";
                q = q.link;
            }
            model.addElement(p.num + Sub);
            p = p.linkNodo;
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Done;
    private javax.swing.JButton Btn_Load;
    private javax.swing.JButton Btn_Save;
    private javax.swing.JFileChooser FileChooser;
    private javax.swing.JList<String> List;
    private javax.swing.JTable Matrix_Adj;
    private javax.swing.JSpinner Vertices;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
